"""Create Phase 2 domain schema

Revision ID: bf5875cd0f81
Revises: 36cca7782ad0
Create Date: 2026-09-20 19:20:20.161126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5875cd0f81'
down_revision = '36cca7782ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'academic_year', name='uq_classes_name_year')
    )
    op.create_table('error_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('mastery_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('mastery_threshold >= 0 AND mastery_threshold <= 100', name='ck_topics_mastery_threshold'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'order_index', name='uq_topics_subject_order'),
    sa.UniqueConstraint('subject_id', 'title', name='uq_topics_subject_title')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_subject_id'), ['subject_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.DateTime(), nullable=False),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("assessment_type IN ('diagnostic', 'practice', 'reassessment')", name='ck_assessments_type'),
    sa.CheckConstraint("status IN ('draft', 'published', 'closed')", name='ck_assessments_status'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'class_id', name='uq_assessments_title_class')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_topic_id'), ['topic_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'withdrawn')", name='ck_enrollments_status'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_id', name='uq_enrollments_student_class')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)

    op.create_table('prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('required_topic_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('topic_id <> required_topic_id', name='ck_prerequisites_distinct_topics'),
    sa.ForeignKeyConstraint(['required_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'required_topic_id', name='uq_prerequisites_pair')
    )
    with op.batch_alter_table('prerequisites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prerequisites_required_topic_id'), ['required_topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prerequisites_topic_id'), ['topic_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term_label', sa.String(length=50), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("report_type IN ('student', 'class', 'analytics')", name='ck_reports_type'),
    sa.CheckConstraint("status IN ('generated', 'failed', 'archived')", name='ck_reports_status'),
    sa.CheckConstraint('student_id IS NOT NULL OR class_id IS NOT NULL', name='ck_reports_has_target'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_subject_id'), ['subject_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('url_or_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 3', name='ck_resources_difficulty'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'title', name='uq_resources_topic_title')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_topic_id'), ['topic_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'name', name='uq_skills_topic_name')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_topic_id'), ['topic_id'], unique=False)

    op.create_table('teacher_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'class_id', 'subject_id', name='uq_teacher_class_subject')
    )
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_assignments_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attempt_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("attempt_type IN ('diagnostic', 'practice', 'reassessment')", name='ck_attempts_type'),
    sa.CheckConstraint("status IN ('in_progress', 'submitted', 'scored', 'processing_failed')", name='ck_attempts_status'),
    sa.CheckConstraint('percentage IS NULL OR (percentage >= 0 AND percentage <= 100)', name='ck_attempts_percentage'),
    sa.CheckConstraint('score IS NULL OR score >= 0', name='ck_attempts_score'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', name='uq_attempts_assessment_student')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_student_id'), ['student_id'], unique=False)

    op.create_table('error_pattern_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('error_tag_id', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('suspected', 'reviewed', 'dismissed', 'overridden')", name='ck_error_flags_status'),
    sa.CheckConstraint('evidence_count >= 0', name='ck_error_flags_evidence'),
    sa.CheckConstraint('incorrect_count >= 0', name='ck_error_flags_incorrect'),
    sa.CheckConstraint('match_count >= 0', name='ck_error_flags_matches'),
    sa.ForeignKeyConstraint(['error_tag_id'], ['error_tags.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_pattern_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_pattern_flags_error_tag_id'), ['error_tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_pattern_flags_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_pattern_flags_topic_id'), ['topic_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("question_type IN ('mcq', 'numeric', 'short_text')", name='ck_questions_type'),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 3', name='ck_questions_difficulty'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'question_text', name='uq_questions_topic_text')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("priority IN ('high', 'medium', 'low')", name='ck_recommendations_priority'),
    sa.CheckConstraint("status IN ('generated', 'viewed', 'in_progress', 'completed', 'dismissed')", name='ck_recommendations_status'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_topic_id'), ['topic_id'], unique=False)

    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('detected_error_tag_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('time_spent_seconds >= 0', name='ck_answers_time_spent_seconds'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detected_error_tag_id'], ['error_tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_answers_attempt_question')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_question_id'), ['question_id'], unique=False)

    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'order_index', name='uq_assessment_questions_order'),
    sa.UniqueConstraint('assessment_id', 'question_id', name='uq_assessment_questions_pair')
    )
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_questions_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_questions_question_id'), ['question_id'], unique=False)

    op.create_table('error_pattern_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_pattern_flag_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('replacement_error_tag_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("decision IN ('confirmed', 'dismissed', 'overridden')", name='ck_error_reviews_decision'),
    sa.ForeignKeyConstraint(['error_pattern_flag_id'], ['error_pattern_flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replacement_error_tag_id'], ['error_tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_pattern_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_pattern_reviews_error_pattern_flag_id'), ['error_pattern_flag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_pattern_reviews_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('error_pattern_flag_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reassessment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('suggested', 'reviewed', 'assigned', 'in_progress', 'reassessment_pending', 'completed', 'closed', 'dismissed')", name='ck_interventions_status'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['error_pattern_flag_id'], ['error_pattern_flags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reassessment_id'], ['assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interventions_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interventions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interventions_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interventions_topic_id'), ['topic_id'], unique=False)

    op.create_table('mastery_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('accuracy_component', sa.Float(), nullable=True),
    sa.Column('difficulty_component', sa.Float(), nullable=True),
    sa.Column('recency_component', sa.Float(), nullable=True),
    sa.Column('trend_component', sa.Float(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('source_attempt_start_id', sa.Integer(), nullable=True),
    sa.Column('source_attempt_end_id', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.CheckConstraint('evidence_count >= 0', name='ck_mastery_records_evidence'),
    sa.CheckConstraint('mastery_score >= 0 AND mastery_score <= 100', name='ck_mastery_records_score'),
    sa.ForeignKeyConstraint(['source_attempt_end_id'], ['attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_attempt_start_id'], ['attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mastery_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mastery_records_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mastery_records_topic_id'), ['topic_id'], unique=False)

    op.create_table('question_error_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('error_tag_id', sa.Integer(), nullable=False),
    sa.Column('option_or_pattern', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['error_tag_id'], ['error_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'error_tag_id', name='uq_question_error_tags_pair')
    )
    with op.batch_alter_table('question_error_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_error_tags_error_tag_id'), ['error_tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_error_tags_question_id'), ['question_id'], unique=False)

    op.create_table('recommendation_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('target_topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("action_type IN ('resource', 'practice', 'reassessment', 'next_topic')", name='ck_recommendation_actions_type'),
    sa.CheckConstraint("status IN ('pending', 'started', 'completed', 'skipped')", name='ck_recommendation_actions_status'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', 'order_index', name='uq_recommendation_actions_order')
    )
    with op.batch_alter_table('recommendation_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_actions_recommendation_id'), ['recommendation_id'], unique=False)

    op.create_table('intervention_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('before_mastery', sa.Float(), nullable=True),
    sa.Column('after_mastery', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('assigned', 'in_progress', 'completed', 'reassessment_pending', 'closed')", name='ck_intervention_students_status'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intervention_id', 'student_id', name='uq_intervention_students_pair')
    )
    with op.batch_alter_table('intervention_students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intervention_students_intervention_id'), ['intervention_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intervention_students_student_id'), ['student_id'], unique=False)

    op.create_table('learning_gain_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('diagnostic_attempt_id', sa.Integer(), nullable=False),
    sa.Column('reassessment_attempt_id', sa.Integer(), nullable=False),
    sa.Column('pre_score', sa.Float(), nullable=False),
    sa.Column('post_score', sa.Float(), nullable=False),
    sa.Column('score_gain', sa.Float(), nullable=False),
    sa.Column('before_mastery', sa.Float(), nullable=True),
    sa.Column('after_mastery', sa.Float(), nullable=True),
    sa.Column('mastery_gain', sa.Float(), nullable=True),
    sa.Column('calculation_version', sa.String(length=50), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_attempt_id'], ['attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reassessment_attempt_id'], ['attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnostic_attempt_id', 'reassessment_attempt_id', name='uq_learning_gain_attempt_pair')
    )
    with op.batch_alter_table('learning_gain_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_gain_records_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_gain_records_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    op.drop_table('learning_gain_records')
    op.drop_table('intervention_students')
    op.drop_table('interventions')
    op.drop_table('recommendation_actions')
    op.drop_table('recommendations')
    op.drop_table('mastery_records')
    op.drop_table('error_pattern_reviews')
    op.drop_table('error_pattern_flags')
    op.drop_table('answers')
    op.drop_table('assessment_questions')
    op.drop_table('attempts')
    op.drop_table('assessments')
    op.drop_table('question_error_tags')
    op.drop_table('questions')
    op.drop_table('resources')
    op.drop_table('skills')
    op.drop_table('prerequisites')
    op.drop_table('topics')
    op.drop_table('teacher_assignments')
    op.drop_table('enrollments')
    op.drop_table('reports')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('classes')
    op.drop_table('roles')
    op.drop_table('subjects')
    op.drop_table('error_tags')
